### ISSUE TITLE
Watchdog not pulling server - in Docker image

### ISSUE THREAD

**Issue by eldios** [space-wizards/SS14.Watchdog#8]
hey ppl,
I'm working on creating a containerized version for the SS14 Watchdog wrapper, here you can find the Docker image and the GitHub page:

https://hub.docker.com/repository/docker/eldios/ss14-server
https://github.com/eldios/Dockerfiles/tree/master/ss14

the problem I'm having right now is that while the watchdog itself seems to be starting, the test instances I configured (here https://github.com/eldios/Dockerfiles/blob/master/ss14/appsettings.yml#L20 ) does NOT seem to pull the latest server nor to start... any idea or hint?

I'm quite positive it's just a configuration issue with the `appsettings.yml` file.

Once we make this working, we can start advertising it in the proper channels as I saw there was no Docker container yet.

Thanks 🙏

**Comment by PJB3005** [comment]
That configuration file looks correct so I'm not sure what the problem is, but this did make me realize I never updated the server hosting guide to use the new Serilog configuration. 

Minimal example for console logging should look something like this:

```yml
Serilog:
  Using: [ "Serilog.Sinks.Console" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Information
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]
```

But on our servers we use this so we have them dump into Loki:

```yml
Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Information
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

  Loki:
    Address: "{{ loki_addr }}"
    Name: "{{ server_id }}"
    Username: "{{ loki_user }}"
    password: "{{ loki_pass }}"
```
